package jogo;

public enum EstadoJogo {
	
	/**
	 * Estados utilizados pelo servidor
	 */
	SERVIDOR_ESPERANDO_CONEXOES_JOGADORES,
	SERVIDOR_ESPERANDO_ESCOLHAS_PERSONAGENS,
	SERVIDOR_ESPERANDO_JOGADAS,
	SERVIDOR_ANALISA_JOGADAS,
	SERVIDOR_FIM_DE_JOGO,
	
	/**
	 * Estados utilizados pelo cliente
	 */
	CLIENTE_CONECTANDO_AO_SERVIDOR,		//Estado utilizado apenas pelo cliente
//	CLIENTE_ESPERANDO_TODOS_JOGADORES_CONECTAREM,
	CLIENTE_ESCOLHENDO_PERSONAGENS,
//	CLIENTE_ESPERANDO_TODOS_JOGADORES_ESCOLHEREM_PERSONSAGENS,
	CLIENTE_ESCOLHENDO_JOGADA,
	CLIENTE_ESPERANDO_JOGADA_ADVERSARIO,
}
